[package]
name = "base64_pcm_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
clap = { version = "4.4.0", features = ["derive"] }
rodio = "0.17.1"
